// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(6)]
    [uFrame.Attributes.uFrameIdentifier("f0f55f11-81ed-4986-aa63-e46f940aaa93")]
    public partial class edText : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _Properties;
        
        private Subject<PropertyChangedEvent<Int32>> _PropertiesObservable;
        
        private PropertyChangedEvent<Int32> _PropertiesEvent;
        
        public override int ComponentId {
            get {
                return 6;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> PropertiesObservable {
            get {
                return _PropertiesObservable ?? (_PropertiesObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 Properties {
            get {
                return _Properties;
            }
            set {
                SetProperties(value);
            }
        }
        
        public virtual void SetProperties(Int32 value) {
            SetProperty(ref _Properties, value, ref _PropertiesEvent, _PropertiesObservable);
        }
    }
}
