// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class HealthSystemclickedHandler {
        
        public Orc entity;
        
        private test.clicked _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int ActionNode20_a = default( System.Int32 );
        
        private int ActionNode20_b = default( System.Int32 );
        
        private int IntNode18 = 10;
        
        private int ActionNode20_Result = default( System.Int32 );
        
        public test.clicked Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode20_a = entity.HealthComp.leben;
            ActionNode20_b = IntNode18;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode20_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode20_a, ActionNode20_b);
            // SetVariableNode
            entity.HealthComp.leben = (System.Int32)ActionNode20_Result;
        }
    }
}
