// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    
    
    [uFrame.Attributes.ComponentId(1)]
    public partial class Orc : uFrame.ECS.Components.GroupItem {
        
        private SwordComp _SwordComp;
        
        private HealthComp _HealthComp;
        
        private ShieldComp _ShieldComp;
        
        public SwordComp SwordComp {
            get {
                return _SwordComp;
            }
            set {
                _SwordComp = value;
            }
        }
        
        public HealthComp HealthComp {
            get {
                return _HealthComp;
            }
            set {
                _HealthComp = value;
            }
        }
        
        public ShieldComp ShieldComp {
            get {
                return _ShieldComp;
            }
            set {
                _ShieldComp = value;
            }
        }
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
    }
}
