// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class DebugSystemBase : uFrame.ECS.Systems.EcsSystem, uFrame.ECS.APIs.ISystemFixedUpdate {
        
        private IEcsComponentManagerOf<TestComponentNode> _TestComponentNodeManager;
        
        private IEcsComponentManagerOf<Orc> _OrcManager;
        
        private IEcsComponentManagerOf<Sword> _SwordManager;
        
        private IEcsComponentManagerOf<Health> _HealthManager;
        
        private IEcsComponentManagerOf<Shield> _ShieldManager;
        
        private DebugSystemGameReadyHandler DebugSystemGameReadyHandlerInstance = new DebugSystemGameReadyHandler();
        
        private DebugSystemFixedUpdateHandler DebugSystemFixedUpdateHandlerInstance = new DebugSystemFixedUpdateHandler();
        
        public IEcsComponentManagerOf<TestComponentNode> TestComponentNodeManager {
            get {
                return _TestComponentNodeManager;
            }
            set {
                _TestComponentNodeManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Orc> OrcManager {
            get {
                return _OrcManager;
            }
            set {
                _OrcManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Sword> SwordManager {
            get {
                return _SwordManager;
            }
            set {
                _SwordManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Health> HealthManager {
            get {
                return _HealthManager;
            }
            set {
                _HealthManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Shield> ShieldManager {
            get {
                return _ShieldManager;
            }
            set {
                _ShieldManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            TestComponentNodeManager = ComponentSystem.RegisterComponent<TestComponentNode>(1);
            OrcManager = ComponentSystem.RegisterGroup<OrcGroup,Orc>();
            SwordManager = ComponentSystem.RegisterComponent<Sword>(4);
            HealthManager = ComponentSystem.RegisterComponent<Health>(2);
            ShieldManager = ComponentSystem.RegisterComponent<Shield>(3);
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ DebugSystemGameReadyFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void DebugSystemGameReadyHandler(uFrame.Kernel.GameReadyEvent data) {
            var handler = DebugSystemGameReadyHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void DebugSystemGameReadyFilter(uFrame.Kernel.GameReadyEvent data) {
            this.DebugSystemGameReadyHandler(data);
        }
        
        protected virtual void DebugSystemFixedUpdateHandler(Orc group) {
            var handler = DebugSystemFixedUpdateHandlerInstance;
            handler.System = this;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void DebugSystemFixedUpdateFilter() {
            var OrcItems = OrcManager.Components;
            for (var OrcIndex = 0
            ; OrcIndex < OrcItems.Count; OrcIndex++
            ) {
                if (!OrcItems[OrcIndex].Enabled) {
                    continue;
                }
                this.DebugSystemFixedUpdateHandler(OrcItems[OrcIndex]);
            }
        }
        
        public virtual void SystemFixedUpdate() {
            DebugSystemFixedUpdateFilter();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("81eb1603-b85d-4aaf-80c9-903965188281")]
    public partial class DebugSystem : DebugSystemBase {
        
        private static DebugSystem _Instance;
        
        public DebugSystem() {
            Instance = this;
        }
        
        public static DebugSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
