// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class inpSysBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<playerComp> _playerCompManager;
        
        private IEcsComponentManagerOf<TestComponentNode> _TestComponentNodeManager;
        
        private IEcsComponentManagerOf<meineTestComp> _meineTestCompManager;
        
        private IEcsComponentManagerOf<NewGroupNode> _NewGroupNodeManager;
        
        private inpSysOnMouseDownHandler inpSysOnMouseDownHandlerInstance = new inpSysOnMouseDownHandler();
        
        public IEcsComponentManagerOf<playerComp> playerCompManager {
            get {
                return _playerCompManager;
            }
            set {
                _playerCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<TestComponentNode> TestComponentNodeManager {
            get {
                return _TestComponentNodeManager;
            }
            set {
                _TestComponentNodeManager = value;
            }
        }
        
        public IEcsComponentManagerOf<meineTestComp> meineTestCompManager {
            get {
                return _meineTestCompManager;
            }
            set {
                _meineTestCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<NewGroupNode> NewGroupNodeManager {
            get {
                return _NewGroupNodeManager;
            }
            set {
                _NewGroupNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            playerCompManager = ComponentSystem.RegisterComponent<playerComp>(3);
            TestComponentNodeManager = ComponentSystem.RegisterComponent<TestComponentNode>(1);
            meineTestCompManager = ComponentSystem.RegisterComponent<meineTestComp>(2);
            NewGroupNodeManager = ComponentSystem.RegisterGroup<NewGroupNodeGroup,NewGroupNode>();
            this.OnEvent<uFrame.ECS.UnityUtilities.MouseDownDispatcher>().Subscribe(_=>{ inpSysOnMouseDownFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void inpSysOnMouseDownHandler(uFrame.ECS.UnityUtilities.MouseDownDispatcher data, playerComp source) {
            var handler = inpSysOnMouseDownHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Source = source;
            StartCoroutine(handler.Execute());
        }
        
        protected void inpSysOnMouseDownFilter(uFrame.ECS.UnityUtilities.MouseDownDispatcher data) {
            var SourceplayerComp = playerCompManager[data.EntityId];
            if (SourceplayerComp == null) {
                return;
            }
            if (!SourceplayerComp.Enabled) {
                return;
            }
            this.inpSysOnMouseDownHandler(data, SourceplayerComp);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("ee14441c-2bf7-40cc-bd91-d0b925d9e670")]
    public partial class inpSys : inpSysBase {
        
        private static inpSys _Instance;
        
        public inpSys() {
            Instance = this;
        }
        
        public static inpSys Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
