// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class InputSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<TestComponentNode> _TestComponentNodeManager;
        
        private IEcsComponentManagerOf<Orc> _OrcManager;
        
        private IEcsComponentManagerOf<Sword> _SwordManager;
        
        private IEcsComponentManagerOf<Health> _HealthManager;
        
        private IEcsComponentManagerOf<Shield> _ShieldManager;
        
        private InputSystemOnMouseDownHandler InputSystemOnMouseDownHandlerInstance = new InputSystemOnMouseDownHandler();
        
        public IEcsComponentManagerOf<TestComponentNode> TestComponentNodeManager {
            get {
                return _TestComponentNodeManager;
            }
            set {
                _TestComponentNodeManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Orc> OrcManager {
            get {
                return _OrcManager;
            }
            set {
                _OrcManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Sword> SwordManager {
            get {
                return _SwordManager;
            }
            set {
                _SwordManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Health> HealthManager {
            get {
                return _HealthManager;
            }
            set {
                _HealthManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Shield> ShieldManager {
            get {
                return _ShieldManager;
            }
            set {
                _ShieldManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            TestComponentNodeManager = ComponentSystem.RegisterComponent<TestComponentNode>(1);
            OrcManager = ComponentSystem.RegisterGroup<OrcGroup,Orc>();
            SwordManager = ComponentSystem.RegisterComponent<Sword>(4);
            HealthManager = ComponentSystem.RegisterComponent<Health>(2);
            ShieldManager = ComponentSystem.RegisterComponent<Shield>(3);
            this.OnEvent<uFrame.ECS.UnityUtilities.MouseDownDispatcher>().Subscribe(_=>{ InputSystemOnMouseDownFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void InputSystemOnMouseDownHandler(uFrame.ECS.UnityUtilities.MouseDownDispatcher data, Orc source) {
            var handler = InputSystemOnMouseDownHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Source = source;
            handler.Execute();
        }
        
        protected void InputSystemOnMouseDownFilter(uFrame.ECS.UnityUtilities.MouseDownDispatcher data) {
            var SourceItem = OrcManager[data.EntityId];
            if (SourceItem == null) {
                return;
            }
            if (!SourceItem.Enabled) {
                return;
            }
            this.InputSystemOnMouseDownHandler(data, SourceItem);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("97f1550b-014b-4a91-b3da-dfe429254d45")]
    public partial class InputSystem : InputSystemBase {
        
        private static InputSystem _Instance;
        
        public InputSystem() {
            Instance = this;
        }
        
        public static InputSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
