// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class levelSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<meineTestComp> _meineTestCompManager;
        
        private IEcsComponentManagerOf<TestComponentNode> _TestComponentNodeManager;
        
        private IEcsComponentManagerOf<playerComp> _playerCompManager;
        
        private IEcsComponentManagerOf<NewGroupNode> _NewGroupNodeManager;
        
        public IEcsComponentManagerOf<meineTestComp> meineTestCompManager {
            get {
                return _meineTestCompManager;
            }
            set {
                _meineTestCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<TestComponentNode> TestComponentNodeManager {
            get {
                return _TestComponentNodeManager;
            }
            set {
                _TestComponentNodeManager = value;
            }
        }
        
        public IEcsComponentManagerOf<playerComp> playerCompManager {
            get {
                return _playerCompManager;
            }
            set {
                _playerCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<NewGroupNode> NewGroupNodeManager {
            get {
                return _NewGroupNodeManager;
            }
            set {
                _NewGroupNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            meineTestCompManager = ComponentSystem.RegisterComponent<meineTestComp>(2);
            TestComponentNodeManager = ComponentSystem.RegisterComponent<TestComponentNode>(1);
            playerCompManager = ComponentSystem.RegisterComponent<playerComp>(3);
            NewGroupNodeManager = ComponentSystem.RegisterGroup<NewGroupNodeGroup,NewGroupNode>();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("1cb84ce4-3032-4b6f-9b06-4dd493ada89d")]
    public partial class levelSystem : levelSystemBase {
        
        private static levelSystem _Instance;
        
        public levelSystem() {
            Instance = this;
        }
        
        public static levelSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
