// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("14d8a89d-b9e1-47a5-8b63-62289c9c4389")]
    public partial class Health : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
    }
}
