// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("247b6845-2fde-4cee-8166-1e6ef40b3079")]
    public partial class meineTestComp : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
    }
}
