// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class NewGroupNodeGroup : ReactiveGroup<NewGroupNode> {
        
        private IEcsComponentManagerOf<playerComp> _playerCompManager;
        
        private IEcsComponentManagerOf<healthComp> _healthCompManager;
        
        private int lastEntityId;
        
        private playerComp playerComp;
        
        private healthComp healthComp;
        
        public IEcsComponentManagerOf<playerComp> playerCompManager {
            get {
                return _playerCompManager;
            }
            set {
                _playerCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<healthComp> healthCompManager {
            get {
                return _healthCompManager;
            }
            set {
                _healthCompManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.APIs.IComponentSystem componentSystem) {
            playerCompManager = componentSystem.RegisterComponent<playerComp>();
            yield return playerCompManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return playerCompManager.RemovedObservable.Select(_=>_.EntityId);;
            healthCompManager = componentSystem.RegisterComponent<healthComp>();
            yield return healthCompManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return healthCompManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((playerComp = playerCompManager[entityId]) == null) {
                return false;
            }
            if ((healthComp = healthCompManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override NewGroupNode Select() {
            var item = new NewGroupNode();;
            item.EntityId = lastEntityId;
            item.playerComp = playerComp;
            item.healthComp = healthComp;
            return item;
        }
    }
}
