// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class healthSysNewEventNodeHandler {
        
        public healthComp clickedEntity;
        
        private test.NewEventNode _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int ActionNode5_a = default( System.Int32 );
        
        private int ActionNode5_b = default( System.Int32 );
        
        private int IntNode4 = 10;
        
        private int ActionNode5_Result = default( System.Int32 );
        
        public test.NewEventNode Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode5_a = clickedEntity.leben;
            ActionNode5_b = IntNode4;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode5_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode5_a, ActionNode5_b);
            // SetVariableNode
            clickedEntity.leben = (System.Int32)ActionNode5_Result;
        }
    }
}
