// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class healthSysBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<healthComp> _healthCompManager;
        
        private IEcsComponentManagerOf<playerComp> _playerCompManager;
        
        private IEcsComponentManagerOf<NewGroupNode> _NewGroupNodeManager;
        
        private healthSysNewEventNodeHandler healthSysNewEventNodeHandlerInstance = new healthSysNewEventNodeHandler();
        
        public IEcsComponentManagerOf<healthComp> healthCompManager {
            get {
                return _healthCompManager;
            }
            set {
                _healthCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<playerComp> playerCompManager {
            get {
                return _playerCompManager;
            }
            set {
                _playerCompManager = value;
            }
        }
        
        public IEcsComponentManagerOf<NewGroupNode> NewGroupNodeManager {
            get {
                return _NewGroupNodeManager;
            }
            set {
                _NewGroupNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            healthCompManager = ComponentSystem.RegisterComponent<healthComp>(2);
            playerCompManager = ComponentSystem.RegisterComponent<playerComp>(3);
            NewGroupNodeManager = ComponentSystem.RegisterGroup<NewGroupNodeGroup,NewGroupNode>();
            this.OnEvent<test.NewEventNode>().Subscribe(_=>{ healthSysNewEventNodeFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void healthSysNewEventNodeHandler(test.NewEventNode data, healthComp clickedentity) {
            var handler = healthSysNewEventNodeHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.clickedEntity = clickedentity;
            handler.Execute();
        }
        
        protected void healthSysNewEventNodeFilter(test.NewEventNode data) {
            var clickedEntityhealthComp = healthCompManager[data.clickedEntity];
            if (clickedEntityhealthComp == null) {
                return;
            }
            if (!clickedEntityhealthComp.Enabled) {
                return;
            }
            this.healthSysNewEventNodeHandler(data, clickedEntityhealthComp);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("5210b204-ff23-4591-aa47-c1fbdbac8164")]
    public partial class healthSys : healthSysBase {
        
        private static healthSys _Instance;
        
        public healthSys() {
            Instance = this;
        }
        
        public static healthSys Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
